### ISSUE TITLE
Crashes if you run after fresh install

### ISSUE THREAD

**Issue by lukepighetti** [Leolainen/figma-plugin-Material-palette#9]
If you install this package and try to run it, it crashes. You have to restart Figma Desktop for it to work.

**Comment by Leolainen** [comment]
@lukepighetti 
Hey! Sorry for the late response!
I cannot reproduce this bug. Are you able to recreate this consistently?

**Comment by lukepighetti** [comment]
I don't have the time to check this for you, so I will close. Thanks!
